pull_request_rules:

  # ===============================================================================
  # DEPENDABOT
  # ===============================================================================

  - name: Automatic Merge for Dependa