pull_request_rules:

  # ===============================================================================
  # DEPENDABOT
  # ===============================================================================

  - name: Automatic Merge for Dependabot Minor Version Pull Requests
    conditions:
      - -draft
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='build (1.16.x, ubuntu-latest)'
      - check-success='build (1.17.x, ubuntu-latest)'
      - check-success='build (1.16.x, macos-latest)'
      - check-success='build (1.17.x, macos-latest)'
      - check-success='lint (1.16.x, ubuntu-latest)'
      - check-success='lint (1.17.x, ubuntu-latest)'
      - check-success='lint (1.16.x, macos-latest)'
      - check-success='lint (1.17.x, macos-latest)'
      - check-success='Analyze (go)'
      - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot pull request
      merge:
        method: squash
  - name: Alert on major version detection
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='build (1.16.x, ubuntu-latest)'
      - check-success='build (1.17.x, ubuntu-latest)'
      - check-success='build (1.16.x, macos-latest)'
      - check-success='build (1.17.x, macos-latest)'
      - check-success='lint (1.16.x, ubuntu-latest)'
      - check-success='lint (1.17.x, ubuntu-latest)'
      - check-success='lint (1.16.x, macos-latest)'
      - check-success='lint (1.17.x, macos-latest)'
      - check-success='Analyze (go)'
      - -title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      comment:
        message: "⚠️ @theflyingcodr @jadwahab: this is a major version bump and requires your attention"


  # ===============================================================================
  # AUTOMATIC MERGE (APPROVALS)
  # ===============================================================================

  - name: Autom