pull_request_rules:

  # ===============================================================================
  # DEPENDABOT
  # ===============================================================================

  - name: Automatic Merge for Dependabot Minor Version Pull Requests
    conditions:
      - -draft
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='build (1.16.x, ubuntu-latest)'
      - check-success='build (1.17.x, ubuntu-latest)'
      - check-success='build (1.16.x, macos-latest)'
      - check-success='build (1.17.x, macos-latest)'
      - check-success='lint (1.16.x, ubuntu-latest)'
      - check-success='lint (1.17.x, ubuntu-latest)'
      - check-success='lint (1.16.x, macos-latest)'
      - check-success='lint (1.17.x, macos-latest)'
      - check-succes